name: Close Issue or PR
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue or PR
        uses: actions/github-script@v5
        with:
          script: |
            const { issue, pull_request } = context.payload;
            const millisecondsInFiveMinutes = 5 * 60 * 1000;
            const delay = () => new Promise(resolve => setTimeout(resolve, millisecondsInFiveMinutes));
            await delay();
            const octokit = github.getOctokit("${{ secrets.GITHUB_TOKEN }}");
            const repo = context.repo;
            const issueOrPrNumber = issue ? issue.number : pull_request.number;
            await octokit.issues.update({
              ...repo,
              issue_number: issueOrPrNumber,
              state: "closed"
            });
